"""Generate FUNCTIONS.md: an index of every function in src/ with its summary.

Agents read FUNCTIONS.md (or use fn_search.py) to locate the right function to
edit without opening every source file. CI runs this with --check and fails on
drift, so the index stays trustworthy.

Usage:
    python tools/functions_index.py --write     # regenerate FUNCTIONS.md
    python tools/functions_index.py --check      # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "FUNCTIONS.md"


def _summary(node: ast.AST) -> str:
    doc = ast.get_docstring(node) or ""
    return doc.strip().splitlines()[0] if doc.strip() else "(no docstring)"


def _signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = [a.arg for a in node.args.args]
    if node.args.vararg:
        args.append("*" + node.args.vararg.arg)
    if node.args.kwarg:
        args.append("**" + node.args.kwarg.arg)
    prefix = "async def " if isinstance(node, ast.AsyncFunctionDef) else "def "
    return f"{prefix}{node.name}({', '.join(args)})"


def collect() -> list[tuple[str, int, str, str]]:
    """Return (relpath, lineno, signature, summary) for every function under src/."""
    rows: list[tuple[str, int, str, str]] = []
    for path in sorted(SRC.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                rows.append((rel, node.lineno, _signature(node), _summary(node)))
    return rows


def render(rows: list[tuple[str, int, str, str]]) -> str:
    lines = [
        "# FUNCTIONS.md",
        "",
        "Auto-generated by `tools/functions_index.py`. Do not edit by hand.",
        "Run `make functions-index` after changing any function.",
        "",
        "| Location | Signature | Summary |",
        "| --- | --- | --- |",
    ]
    for rel, lineno, sig, summary in rows:
        lines.append(f"| `{rel}:{lineno}` | `{sig}` | {summary} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = render(collect())
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    if args.check:
        if content != current:
            print("FUNCTIONS.md is out of date. Run `make functions-index`.", file=sys.stderr)
            return 1
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({content.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
